### ISSUE TITLE
Critical issue after installing

### ISSUE THREAD

**Issue by allowdoc** [U7P4L-IN/U-DDOS#1]
after installing when I tried to start i am getting this issue see in image i tried also other server and pc . all req..  was sucessfull  installed
![image](https://github.com/U7P4L-IN/U-DDOS/assets/122750347/5d26a9f6-5a72-4ebe-90e2-87ffea5e3e50)

**Comment by U7P4L-IN** [comment]
Which tarminal u used

**Comment by allowdoc** [comment]
I tried in different terminal, I used my ssh in putty and I also tried in Google cloud shell terminal, even I just tried in my CentOS root terminal.

I think issue is in your UDDOs.py main program file Nom utf8 code starting with '\xa7' on line one. Also may the this python file is encrypted or curropted

**Comment by U7P4L-IN** [comment]
Use kali linux or tarmux

**Comment by allowdoc** [comment]
Just tried in kali linux 2023 not working same issue. May be the.py file is curropted. Please run it or make video. Not working bro

**Comment by U7P4L-IN** [comment]
Ok wait for tutorial video
