### ISSUE TITLE
U-DDOS.py file broken It's encoding type is not UTF-8 or it is corrupted. 

### ISSUE THREAD

**Issue by RetroClones** [U7P4L-IN/U-DDOS#4]
U-DDOS.py file Its encoding type is not UTF-8 or it is corrupted. If you try to open, it does not work as intended making the whole thing pointless. I've attempted to use Kali and Tarmux terminal didn't work either it's a shame because it looks like an excellent tool.

**Comment by U7P4L-IN** [comment]
Ck this `https://t.me/ANONYMOUS_DISCUSSI0N/42408`
